Warning: Permanently added '172.31.41.50' (ECDSA) to the list of known hosts.
Warning: Permanently added '172.31.42.94' (ECDSA) to the list of known hosts.
Warning: Permanently added '172.31.35.206' (ECDSA) to the list of known hosts.
/home/ubuntu/pyranda/install_location_pyranda/lib/python2.7/site-packages/pyranda/pyrandaBC.py:390: RuntimeWarning: invalid value encountered in divide
  self.pyranda.variables[velocity[uu]].data[0,:,:]*mag0/magF,
/home/ubuntu/pyranda/install_location_pyranda/lib/python2.7/site-packages/pyranda/pyrandaBC.py:390: RuntimeWarning: invalid value encountered in divide
  self.pyranda.variables[velocity[uu]].data[0,:,:]*mag0/magF,
/home/ubuntu/pyranda/install_location_pyranda/lib/python2.7/site-packages/pyranda/pyrandaBC.py:390: RuntimeWarning: invalid value encountered in divide
  self.pyranda.variables[velocity[uu]].data[0,:,:]*mag0/magF,
/home/ubuntu/pyranda/install_location_pyranda/lib/python2.7/site-packages/pyranda/pyrandaBC.py:390: RuntimeWarning: invalid value encountered in divide
  self.pyranda.variables[velocity[uu]].data[0,:,:]*mag0/magF,
/home/ubuntu/pyranda/install_location_pyranda/lib/python2.7/site-packages/pyranda/pyrandaBC.py:437: RuntimeWarning: invalid value encountered in divide
  self.pyranda.variables[velocity[uu]].data[-1,:,:]*mag0/magF,
/home/ubuntu/pyranda/install_location_pyranda/lib/python2.7/site-packages/pyranda/pyrandaBC.py:437: RuntimeWarning: invalid value encountered in divide
  self.pyranda.variables[velocity[uu]].data[-1,:,:]*mag0/magF,
/home/ubuntu/pyranda/install_location_pyranda/lib/python2.7/site-packages/pyranda/pyrandaBC.py:437: RuntimeWarning: invalid value encountered in divide
  self.pyranda.variables[velocity[uu]].data[-1,:,:]*mag0/magF,
/home/ubuntu/pyranda/install_location_pyranda/lib/python2.7/site-packages/pyranda/pyrandaBC.py:437: RuntimeWarning: invalid value encountered in divide
  self.pyranda.variables[velocity[uu]].data[-1,:,:]*mag0/magF,
/home/ubuntu/pyranda/install_location_pyranda/lib/python2.7/site-packages/pyranda/pyrandaBC.py:295: RuntimeWarning: invalid value encountered in divide
  self.pyranda.variables[velocity[uu]].data[:,0,:]*mag0/magF,
[ip-172-31-40-182:11285] 3 more processes have sent help message help-mpi-btl-base.txt / btl:no-nics
[ip-172-31-40-182:11285] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
